import type {
    Activity,
    Match,
    MatchRequest,
    Review,
    User,
    UserActivityPreference,
} from '@/types';

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Naledi Mokoena',
    email: 'naledi@example.com',
    phone: '+27 71 234 5678',
    gender: 'woman',
    age: 28,
    profilePhoto: '',
    bio: 'Trail runner and coffee enthusiast. Always looking for someone to explore new hiking routes with on weekends.',
    city: 'Cape Town',
    country: 'South Africa',
    verified: true,
    trustScore: 4.8,
    createdAt: new Date('2025-09-15'),
  },
  {
    id: 'u2',
    name: 'Amara Osei',
    email: 'amara@example.com',
    phone: '+44 7700 900123',
    gender: 'woman',
    age: 32,
    profilePhoto: '',
    bio: 'Art lover and museum wanderer. Film festivals are my weekend ritual.',
    city: 'Cape Town',
    country: 'South Africa',
    verified: true,
    trustScore: 4.6,
    createdAt: new Date('2025-10-02'),
  },
  {
    id: 'u3',
    name: 'Lerato Dlamini',
    email: 'lerato@example.com',
    phone: '+27 82 345 6789',
    gender: 'woman',
    age: 25,
    profilePhoto: '',
    bio: 'Foodie who believes every meal is better with company. Concert lover on the side.',
    city: 'Cape Town',
    country: 'South Africa',
    verified: true,
    trustScore: 4.9,
    createdAt: new Date('2025-08-20'),
  },
  {
    id: 'u4',
    name: 'Thabo Molefe',
    email: 'thabo@example.com',
    phone: '+27 73 456 7890',
    gender: 'man',
    age: 30,
    profilePhoto: '',
    bio: 'Weekend hiker, weekday runner. Always up for an outdoor adventure.',
    city: 'Cape Town',
    country: 'South Africa',
    verified: false,
    trustScore: 4.2,
    createdAt: new Date('2025-11-01'),
  },
  {
    id: 'u5',
    name: 'Zara Ndlovu',
    email: 'zara@example.com',
    phone: '+27 84 567 8901',
    gender: 'woman',
    age: 27,
    profilePhoto: '',
    bio: 'Film buff and gallery hopper. Looking for someone to share the experience with.',
    city: 'Cape Town',
    country: 'South Africa',
    verified: true,
    trustScore: 4.7,
    createdAt: new Date('2025-10-18'),
  },
];

export const CURRENT_USER = MOCK_USERS[0];

export const MOCK_ACTIVITIES: (Activity & { posterName: string; posterTrustScore: number; categoryName: string; categoryIcon: string })[] = [
  {
    id: 'a1',
    userId: 'u2',
    categoryId: 'museums',
    title: 'Zeitz MOCAA Sunday Visit',
    description: 'Planning to spend a Sunday afternoon exploring the Zeitz MOCAA contemporary art museum. Would love a companion to discuss the exhibitions with.',
    dateTime: new Date('2026-04-06T14:00:00'),
    neighborhood: 'V&A Waterfront',
    coordinates: { lat: -33.9087, lng: 18.4171 },
    city: 'Cape Town',
    country: 'South Africa',
    companionCount: 1,
    status: 'open',
    createdAt: new Date('2026-03-28'),
    posterName: 'Amara O.',
    posterTrustScore: 4.6,
    categoryName: 'museums',
    categoryIcon: '🏛️',
  },
  {
    id: 'a2',
    userId: 'u3',
    categoryId: 'dining',
    title: 'Woodstock Street Food Tour',
    description: 'Let\'s explore the best street food spots in Woodstock. I\'ve mapped out about 5 stops — everything from bunny chow to artisanal gelato.',
    dateTime: new Date('2026-04-05T12:00:00'),
    neighborhood: 'Woodstock',
    coordinates: { lat: -33.9290, lng: 18.4440 },
    city: 'Cape Town',
    country: 'South Africa',
    companionCount: 3,
    status: 'open',
    createdAt: new Date('2026-03-30'),
    posterName: 'Lerato D.',
    posterTrustScore: 4.9,
    categoryName: 'dining',
    categoryIcon: '🍽️',
  },
  {
    id: 'a3',
    userId: 'u4',
    categoryId: 'hiking',
    title: 'Lion\'s Head Sunrise Hike',
    description: 'Early morning hike up Lion\'s Head to catch the sunrise. Meeting at the parking area at 5:30 AM. Moderate fitness required.',
    dateTime: new Date('2026-04-07T05:30:00'),
    neighborhood: 'Signal Hill',
    coordinates: { lat: -33.9365, lng: 18.3896 },
    city: 'Cape Town',
    country: 'South Africa',
    companionCount: 2,
    status: 'open',
    createdAt: new Date('2026-03-29'),
    posterName: 'Thabo M.',
    posterTrustScore: 4.2,
    categoryName: 'hiking',
    categoryIcon: '🥾',
  },
  {
    id: 'a4',
    userId: 'u5',
    categoryId: 'film',
    title: 'Labia Theatre Double Feature',
    description: 'The Labia is showing a double feature of classic French films this Saturday. Anyone keen to watch and grab coffee after?',
    dateTime: new Date('2026-04-04T18:00:00'),
    neighborhood: 'Gardens',
    coordinates: { lat: -33.9350, lng: 18.4101 },
    city: 'Cape Town',
    country: 'South Africa',
    companionCount: 1,
    status: 'open',
    createdAt: new Date('2026-04-01'),
    posterName: 'Zara N.',
    posterTrustScore: 4.7,
    categoryName: 'film',
    categoryIcon: '🎬',
  },
  {
    id: 'a5',
    userId: 'u3',
    categoryId: 'concerts',
    title: 'Jazz at The Crypt',
    description: 'Live jazz night at The Crypt in the basement of St George\'s Cathedral. Great acoustics and intimate setting.',
    dateTime: new Date('2026-04-08T20:00:00'),
    neighborhood: 'City Centre',
    coordinates: { lat: -33.9260, lng: 18.4185 },
    city: 'Cape Town',
    country: 'South Africa',
    companionCount: 1,
    status: 'open',
    createdAt: new Date('2026-04-02'),
    posterName: 'Lerato D.',
    posterTrustScore: 4.9,
    categoryName: 'concerts',
    categoryIcon: '🎵',
  },
  {
    id: 'a6',
    userId: 'u1',
    categoryId: 'running',
    recurrenceRule: 'weekly:saturday',
    title: 'Sea Point Promenade Parkrun',
    description: 'Weekly Saturday morning parkrun along the Sea Point Promenade. All paces welcome — just show up and move.',
    neighborhood: 'Sea Point',
    coordinates: { lat: -33.9170, lng: 18.3855 },
    city: 'Cape Town',
    country: 'South Africa',
    companionCount: 4,
    status: 'open',
    createdAt: new Date('2026-03-15'),
    posterName: 'Naledi M.',
    posterTrustScore: 4.8,
    categoryName: 'running',
    categoryIcon: '🏃',
  },
  {
    id: 'a7',
    userId: 'u2',
    categoryId: 'art',
    title: 'First Thursdays Gallery Walk',
    description: 'It\'s First Thursdays! Let\'s walk the galleries along Bree Street and grab wine between stops.',
    dateTime: new Date('2026-04-09T18:00:00'),
    neighborhood: 'City Centre',
    coordinates: { lat: -33.9220, lng: 18.4200 },
    city: 'Cape Town',
    country: 'South Africa',
    companionCount: 2,
    status: 'open',
    createdAt: new Date('2026-04-02'),
    posterName: 'Amara O.',
    posterTrustScore: 4.6,
    categoryName: 'art',
    categoryIcon: '🎨',
  },
  {
    id: 'a8',
    userId: 'u5',
    categoryId: 'travel',
    title: 'Day Trip to Franschhoek',
    description: 'Planning a wine tasting day trip to Franschhoek. Happy to drive — just need a co-explorer. Will hit 3-4 estates.',
    dateTime: new Date('2026-04-12T09:00:00'),
    neighborhood: 'Cape Town',
    coordinates: { lat: -33.9120, lng: 18.4023 },
    city: 'Cape Town',
    country: 'South Africa',
    companionCount: 1,
    status: 'open',
    createdAt: new Date('2026-04-03'),
    posterName: 'Zara N.',
    posterTrustScore: 4.7,
    categoryName: 'travel',
    categoryIcon: '✈️',
  },
];

export const MOCK_MATCH_REQUESTS: (MatchRequest & { requesterName: string; requesterTrustScore: number })[] = [
  {
    id: 'mr1',
    activityId: 'a6',
    requesterId: 'u2',
    status: 'pending',
    createdAt: new Date('2026-04-02'),
    requesterName: 'Amara O.',
    requesterTrustScore: 4.6,
  },
  {
    id: 'mr2',
    activityId: 'a6',
    requesterId: 'u5',
    status: 'pending',
    createdAt: new Date('2026-04-03'),
    requesterName: 'Zara N.',
    requesterTrustScore: 4.7,
  },
];

export const MOCK_MATCHES: (Match & {
  activityTitle: string;
  categoryIcon: string;
  categoryName: string;
  companionName: string;
  companionTrustScore: number;
  dateLabel: string;
  neighborhood: string;
})[] = [
  {
    id: 'm1',
    activityId: 'a1',
    user1Id: 'u1',
    user2Id: 'u2',
    status: 'confirmed',
    createdAt: new Date('2026-04-01'),
    activityTitle: 'Zeitz MOCAA Sunday Visit',
    categoryIcon: '🏛️',
    categoryName: 'museums',
    companionName: 'Amara O.',
    companionTrustScore: 4.6,
    dateLabel: 'Sun, Apr 6 · 2:00 PM',
    neighborhood: 'V&A Waterfront',
  },
  {
    id: 'm2',
    activityId: 'a4',
    user1Id: 'u1',
    user2Id: 'u5',
    status: 'confirmed',
    createdAt: new Date('2026-04-02'),
    activityTitle: 'Labia Theatre Double Feature',
    categoryIcon: '🎬',
    categoryName: 'film',
    companionName: 'Zara N.',
    companionTrustScore: 4.7,
    dateLabel: 'Sat, Apr 4 · 6:00 PM',
    neighborhood: 'Gardens',
  },
  {
    id: 'm3',
    activityId: 'a3',
    user1Id: 'u1',
    user2Id: 'u4',
    status: 'completed',
    createdAt: new Date('2026-03-20'),
    activityTitle: 'Table Mountain Hike',
    categoryIcon: '🥾',
    categoryName: 'hiking',
    companionName: 'Thabo M.',
    companionTrustScore: 4.2,
    dateLabel: 'Sat, Mar 22',
    neighborhood: 'Camps Bay',
  },
];

export const MOCK_REVIEWS: (Review & { reviewerName: string; comment?: string })[] = [
  {
    id: 'r1',
    matchId: 'm3',
    reviewerId: 'u4',
    revieweeId: 'u1',
    rating: 5,
    flagged: false,
    createdAt: new Date('2026-03-23'),
    reviewerName: 'Thabo M.',
    comment: 'Great hiking companion — set a good pace and had really interesting conversation along the way.',
  },
  {
    id: 'r2',
    matchId: 'm3',
    reviewerId: 'u2',
    revieweeId: 'u1',
    rating: 5,
    flagged: false,
    createdAt: new Date('2026-03-10'),
    reviewerName: 'Amara O.',
    comment: 'Naledi was lovely to explore the gallery with. Would definitely do another activity together.',
  },
  {
    id: 'r3',
    matchId: 'm3',
    reviewerId: 'u3',
    revieweeId: 'u1',
    rating: 4,
    flagged: false,
    createdAt: new Date('2026-02-28'),
    reviewerName: 'Lerato D.',
    comment: 'Fun dinner companion. Was punctual and great with trying new food.',
  },
];

export const MOCK_PREFERENCES: UserActivityPreference[] = [
  {
    userId: 'u1',
    categoryId: 'hiking',
    skillLevel: 'intermediate',
    preferredCompanionGender: 'women-only',
    preferredAgeRangeMin: 24,
    preferredAgeRangeMax: 38,
  },
  {
    userId: 'u1',
    categoryId: 'running',
    skillLevel: 'experienced',
    preferredCompanionGender: 'any',
    preferredAgeRangeMin: 22,
    preferredAgeRangeMax: 40,
  },
  {
    userId: 'u1',
    categoryId: 'dining',
    skillLevel: 'beginner',
    preferredCompanionGender: 'no-preference',
    preferredAgeRangeMin: 20,
    preferredAgeRangeMax: 45,
  },
  {
    userId: 'u1',
    categoryId: 'art',
    skillLevel: 'beginner',
    preferredCompanionGender: 'women-only',
    preferredAgeRangeMin: 24,
    preferredAgeRangeMax: 40,
  },
];

export const MOCK_CHAT_MESSAGES = [
  { id: 'c1', text: 'Hey! Excited for the museum visit on Sunday.', timestamp: '10:32 AM', isSent: false },
  { id: 'c2', text: 'Me too! I\'ve been wanting to see the new Zanele Muholi exhibition.', timestamp: '10:33 AM', isSent: true },
  { id: 'c3', text: 'Yes! That\'s the one I\'m most looking forward to. Should we meet at the entrance?', timestamp: '10:34 AM', isSent: false },
  { id: 'c4', text: 'Sounds good. I\'ll be there at 2. I\'ll be wearing a denim jacket.', timestamp: '10:35 AM', isSent: true },
  { id: 'c5', text: 'Perfect. See you then! 🙌', timestamp: '10:35 AM', isSent: false },
  { id: 'c6', text: 'Do you want to grab coffee at the museum cafe after?', timestamp: '10:40 AM', isSent: true },
  { id: 'c7', text: 'Absolutely, I love their flat whites.', timestamp: '10:42 AM', isSent: false },
];

export function formatActivityDate(date?: Date): string {
  if (!date) return 'Recurring';
  const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  const d = new Date(date);
  const hours = d.getHours();
  const minutes = d.getMinutes();
  const ampm = hours >= 12 ? 'PM' : 'AM';
  const h = hours % 12 || 12;
  const m = minutes.toString().padStart(2, '0');
  return `${days[d.getDay()]}, ${months[d.getMonth()]} ${d.getDate()} · ${h}:${m} ${ampm}`;
}
